import Head from 'next/head'
import React, { useState } from 'react';
import Link from "next/link";
import Styles from "../styles/Home.module.css"
import { useRouter } from 'next/router';

export default function Home() {
  const [name, setName] = useState('');
  const [room, setRoom] = useState('');
  const router = useRouter();

  const handleClick = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (!name || !room) {
      e.preventDefault()
    } else {
      router.push({
        pathname: '/chat',
        query: { name: name, room: room },
      })
    }

  }
  return (
    <div className={Styles.body}>


      <div className={Styles.mainselector}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={Styles.joinOuterContainer}>
          <div className={Styles.joinInnerContainer}>
            <h1 className={Styles.heading}>Join</h1>
            <div>
              <input placeholder="Name" className={Styles.joinInput} type="text" onChange={(event) => setName(event.target.value)} />
            </div>
            <div>
              <input placeholder="Email" className={Styles.joinInput} type="email" />
            </div>
            <div>
              <input placeholder="Password" className={Styles.joinInput} type="password" />
            </div>
            <div>
              <input placeholder="Room" className={Styles.joinInput} type="text" onChange={(event) => setRoom(event.target.value)} />
            </div>
            <Link onClick={e => (!name || !room) ? e.preventDefault() : null} href={`/chat?name=${name}&room=${room}`}>
              <button className={Styles.button} type="submit">Chat Now</button>
            </Link>
          </div>
        </div>

      </div>
    </div>
  )
}
